

// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    query:       string[];
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    id:            string;
    type:          FeatureType;
    place_type:    PlaceType[];
    relevance:     number;
    properties:    Properties;
    text_es:       Text;
    place_name_es: string;
    text:          Text;
    place_name:    string;
    center:        number[];
    geometry:      Geometry;
    address:       string;
    context:       Context[];
}

export interface Context {
    id:           string;
    text_es:      string;
    text:         string;
    wikidata?:    string;
    language_es?: Language;
    language?:    Language;
    short_code?:  Language;
}

export enum Language {
    Es = "es",
    EsCA = "ES-CA",
    EsSE = "ES-SE",
}

export interface Geometry {
    type:          GeometryType;
    coordinates:   number[];
    interpolated?: boolean;
    omitted?:      boolean;
}

export enum GeometryType {
    Point = "Point",
}

export enum PlaceType {
    Address = "address",
}

export interface Properties {
    accuracy: Accuracy;
}

export enum Accuracy {
    Interpolated = "interpolated",
    Point = "point",
    Rooftop = "rooftop",
}

export enum Text {
    CalleGolondrina = "Calle Golondrina",
    Golondrina = "Golondrina",
}

export enum FeatureType {
    Feature = "Feature",
}
